### ISSUE TITLE
Repository needs a license

### ISSUE THREAD

**Issue by oprypin** [pawamoy/mkdocs-gallery#8]

**Comment by pawamoy** [comment]
You mean this repo? Same as catalog/mkdocs is fine to me.

**Comment by oprypin** [comment]
Ah yes I suppose.
Could you add such a license file yourself?

**Comment by pawamoy** [comment]
Sure, will do tomorrow :slightly_smiling_face:

**Comment by oprypin** [comment]
Ping for an update :sweat_smile:

**Comment by pawamoy** [comment]
Oops, forgot about this :P

**Comment by pawamoy** [comment]
Done, same as catalog.
